Repository 9oormthon-univ/2024_DANPOON_TEAM_1_BE, pull requests merged in 2024-11, with the labels that each got.

#2 [init] 깃허브 이슈 & PR 템플릿 생성
  .github/ISSUE_TEMPLATE/chore.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/fix.md
  .github/ISSUE_TEMPLATE/init.md
  .github/ISSUE_TEMPLATE/refactor.md
  .github/ISSUE_TEMPLATE/test.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: :sparkles: feat, :o: init

#5 [feat] CD test2
  Dockerfile
  src/main/java/trend/project/TestController.java
Labels: :construction_worker: cicd, :o: init, :test_tube: test

#6 [feat] CD test3
  src/main/java/trend/project/TestController.java
  src/main/resources/application.yml
  src/test/java/trend/project/ProjectApplicationTests.java
Labels: :construction_worker: cicd, :sparkles: feat, :o: init

#8 [feat] CD test4
  Dockerfile
  src/main/java/trend/project/TestController.java
Labels: :construction_worker: cicd, :o: init, :test_tube: test

#9 [feat] CD test5
  src/main/java/trend/project/TestController.java
Labels: :construction_worker: cicd, :o: init, :test_tube: test

#10 [feat] CD 파이프라인 구축
  src/main/java/trend/project/TestController.java
Labels: :construction_worker: cicd, :sparkles: feat

#12 Init/7
  build.gradle
  src/main/java/trend/project/api/ApiResponse.java
  src/main/java/trend/project/api/code/BaseCode.java
  src/main/java/trend/project/api/code/BaseErrorCode.java
  src/main/java/trend/project/api/code/ErrorReasonDTO.java
  src/main/java/trend/project/api/code/ReasonDTO.java
  src/main/java/trend/project/api/code/status/CommonErrorStatus.java
  src/main/java/trend/project/api/code/status/ErrorStatus.java
  src/main/java/trend/project/api/code/status/SuccessStatus.java
  src/main/java/trend/project/api/exception/ExceptionAdvice.java
  src/main/java/trend/project/api/exception/GeneralException.java
  src/main/java/trend/project/api/exception/UnauthorizedException.java
  src/main/java/trend/project/config/SwaggerConfig.java
Labels: :o: init

#13 [feat] Spring Security 주입 및 로그인 & 회원가입 로직 구현
  .github/workflows/dev_CD.yml
  build.gradle
  src/main/java/trend/project/TestController.java
  src/main/java/trend/project/api/code/status/ErrorStatus.java
  src/main/java/trend/project/api/exception/handler/CompanyCategoryHandler.java
  src/main/java/trend/project/api/exception/handler/MemberCategoryHandler.java
  src/main/java/trend/project/config/SecurityConfig.java
  src/main/java/trend/project/domain/Address.java
  src/main/java/trend/project/domain/Company.java
  src/main/java/trend/project/domain/Member.java
  src/main/java/trend/project/domain/RefreshEntity.java
  src/main/java/trend/project/domain/Role.java
  src/main/java/trend/project/domain/Status.java
  src/main/java/trend/project/filter/CustomLogoutFilter.java
  src/main/java/trend/project/filter/LoginFilter.java
  src/main/java/trend/project/jwt/JWTFilter.java
  src/main/java/trend/project/jwt/JWTUtil.java
  src/main/java/trend/project/repository/AddressRepository.java
  src/main/java/trend/project/repository/CompanyRepository.java
  src/main/java/trend/project/repository/MemberRepository.java
  src/main/java/trend/project/repository/RefreshRepository.java
  src/main/java/trend/project/service/authService/CustomUserDetailsService.java
  src/main/java/trend/project/service/authService/RefreshTokenService.java
  src/main/java/trend/project/service/companyService/CompanyService.java
  src/main/java/trend/project/service/companyService/CompanyServiceImpl.java
  src/main/java/trend/project/service/memberService/MemberService.java
  src/main/java/trend/project/service/memberService/MemberServiceImpl.java
  src/main/java/trend/project/web/controller/CompanyController.java
  src/main/java/trend/project/web/controller/MemberController.java
  src/main/java/trend/project/web/dto/CompanyJoinDTO.java
  src/main/java/trend/project/web/dto/CustomUserDetails.java
  src/main/java/trend/project/web/dto/MemberJoinDTO.java
  src/main/resources/application.yml
Labels: :sparkles: feat

#16 [feat] 도메인 엔티티 구현
  src/main/java/trend/project/domain/Agreement.java
  src/main/java/trend/project/domain/Bookmark.java
  src/main/java/trend/project/domain/Comment.java
  src/main/java/trend/project/domain/CommentLikes.java
  src/main/java/trend/project/domain/Company.java
  src/main/java/trend/project/domain/CompanyProfileImage.java
  src/main/java/trend/project/domain/Location.java
  src/main/java/trend/project/domain/Member.java
  src/main/java/trend/project/domain/MemberFollow.java
  src/main/java/trend/project/domain/MemberFollower.java
  src/main/java/trend/project/domain/MemberProfileImage.java
  src/main/java/trend/project/domain/Plan.java
  src/main/java/trend/project/domain/PlanBannerImage.java
  src/main/java/trend/project/domain/PlanLikes.java
  src/main/java/trend/project/domain/PlanPosterImage.java
  src/main/java/trend/project/domain/PlanRanking.java
  src/main/java/trend/project/domain/common/BaseEntity.java
  src/main/java/trend/project/domain/enumClass/Category.java
  src/main/java/trend/project/domain/enumClass/CommentType.java
  src/main/java/trend/project/domain/enumClass/Gender.java
  src/main/java/trend/project/domain/enumClass/PlanStatus.java
  src/main/java/trend/project/domain/enumClass/Role.java
  src/main/java/trend/project/domain/enumClass/Status.java
  src/main/java/trend/project/jwt/JWTFilter.java
  src/main/java/trend/project/service/companyService/CompanyServiceImpl.java
  src/main/java/trend/project/service/memberService/MemberServiceImpl.java
Labels: :sparkles: feat

#21 기획서 상세 조회 API 구현
  src/main/java/trend/project/api/code/status/ErrorStatus.java
  src/main/java/trend/project/api/exception/handler/PlanCategoryHandler.java
  src/main/java/trend/project/converter/PlanConverter.java
  src/main/java/trend/project/repository/planRepository/BannerImageRepository.java
  src/main/java/trend/project/repository/planRepository/LocationRepository.java
  src/main/java/trend/project/repository/planRepository/PlanRepository.java
  src/main/java/trend/project/repository/planRepository/PosterImageRepository.java
  src/main/java/trend/project/service/planService/PlanService.java
  src/main/java/trend/project/service/planService/PlanServiceImpl.java
  src/main/java/trend/project/web/controller/planController/PlanController.java
  src/main/java/trend/project/web/dto/planDTO/PlanDTO.java
  src/main/java/trend/project/web/dto/planDTO/PlanDetailDTO.java
Labels: :sparkles: feat

#23 [feat] S3 주입 및 회원&기업 프로필 이미지 CRUD 구현
  build.gradle
  src/main/java/trend/project/api/code/status/ErrorStatus.java
  src/main/java/trend/project/api/exception/handler/ImageCategoryHandler.java
  src/main/java/trend/project/config/S3Config.java
  src/main/java/trend/project/domain/Company.java
  src/main/java/trend/project/domain/Member.java
  src/main/java/trend/project/repository/CompanyProfileImageRepository.java
  src/main/java/trend/project/repository/MemberProfileImageRepository.java
  src/main/java/trend/project/service/companyService/CompanyProfileImageService.java
  src/main/java/trend/project/service/companyService/CompanyProfileImageServiceImpl.java
  src/main/java/trend/project/service/memberService/MemberProfileImageService.java
  src/main/java/trend/project/service/memberService/MemberProfileImageServiceImpl.java
  src/main/java/trend/project/web/controller/CompanyImageController.java
  src/main/java/trend/project/web/controller/MemberImageController.java
  src/main/resources/application.yml
Labels: :sparkles: feat

#24 게시글 관련 댓글 조회 API 구현
  src/main/java/trend/project/config/SecurityConfig.java
  src/main/java/trend/project/converter/CommentConverter.java
  src/main/java/trend/project/repository/CommentRepository.java
  src/main/java/trend/project/service/commentService/CommentService.java
  src/main/java/trend/project/service/commentService/CommentServiceImpl.java
  src/main/java/trend/project/web/controller/commentController/CommentController.java
  src/main/java/trend/project/web/dto/commentDTO/CommentDTO.java
Labels: :sparkles: feat

#26 [Feature] 기획서 생성 API 구현
  src/main/java/trend/project/api/code/status/ErrorStatus.java
  src/main/java/trend/project/converter/LocationConverter.java
  src/main/java/trend/project/converter/PlanConverter.java
  src/main/java/trend/project/domain/Plan.java
  src/main/java/trend/project/service/planService/PlanService.java
  src/main/java/trend/project/service/planService/PlanServiceImpl.java
  src/main/java/trend/project/web/controller/planController/PlanController.java
  src/main/java/trend/project/web/dto/planDTO/PlanDTO.java
Labels: :sparkles: feat

#29 [feat] 헬스체크 api 구현
  src/main/java/trend/project/config/SecurityConfig.java
  src/main/java/trend/project/web/controller/HealthCheckController.java
Labels: :sparkles: feat

#30 [feat] 기획서 이미지, 배너 관련 API 구현
  src/main/java/trend/project/api/code/status/ErrorStatus.java
  src/main/java/trend/project/config/SecurityConfig.java
  src/main/java/trend/project/converter/PlanConverter.java
  src/main/java/trend/project/domain/PlanBannerImage.java
  src/main/java/trend/project/domain/PlanPosterImage.java
  src/main/java/trend/project/repository/planRepository/BannerImageRepository.java
  src/main/java/trend/project/service/planService/PlanBannerService.java
  src/main/java/trend/project/service/planService/PlanBannerServiceImpl.java
  src/main/java/trend/project/service/planService/PlanPosterService.java
  src/main/java/trend/project/service/planService/PlanPosterServiceImpl.java
  src/main/java/trend/project/service/planService/PlanServiceImpl.java
  src/main/java/trend/project/web/controller/planController/PlanBannerController.java
  src/main/java/trend/project/web/controller/planController/PlanPosterController.java
Labels: :sparkles: feat

#32 [chore] 댓글 엔티티 유형 필드 삭제 및 관련 로직 수정
  src/main/java/trend/project/converter/CommentConverter.java
  src/main/java/trend/project/domain/Comment.java
  src/main/java/trend/project/web/dto/commentDTO/CommentDTO.java
Labels: :pencil2: chore

#33 [feat] 회원 기능 구현
  src/main/java/trend/project/api/code/status/ErrorStatus.java
  src/main/java/trend/project/config/SecurityConfig.java
  src/main/java/trend/project/domain/Member.java
  src/main/java/trend/project/domain/Plan.java
  src/main/java/trend/project/filter/LoginFilter.java
  src/main/java/trend/project/repository/CompanyRepository.java
  src/main/java/trend/project/repository/MemberRepository.java
  src/main/java/trend/project/service/companyService/CompanyService.java
  src/main/java/trend/project/service/companyService/CompanyServiceImpl.java
  src/main/java/trend/project/service/memberService/MemberService.java
  src/main/java/trend/project/service/memberService/MemberServiceImpl.java
  src/main/java/trend/project/web/controller/CompanyController.java
  src/main/java/trend/project/web/controller/MemberController.java
  src/main/java/trend/project/web/controller/companyController/CompanyController.java
  src/main/java/trend/project/web/controller/companyController/CompanyImageController.java
  src/main/java/trend/project/web/controller/memberController/MemberController.java
  src/main/java/trend/project/web/controller/memberController/MemberImageController.java
  src/main/java/trend/project/web/dto/companyDTO/CompanyJoinDTO.java
  src/main/java/trend/project/web/dto/companyDTO/CompanyProfileFindDTO.java
  src/main/java/trend/project/web/dto/companyDTO/CompanyProfileUpdateDTO.java
  src/main/java/trend/project/web/dto/memberDTO/MemberGetProfileDTO.java
  src/main/java/trend/project/web/dto/memberDTO/MemberJoinDTO.java
  src/main/java/trend/project/web/dto/memberDTO/MemberProfileFindDTO.java
  src/main/java/trend/project/web/dto/memberDTO/MemberProfileImageDTO.java
  src/main/java/trend/project/web/dto/memberDTO/MemberProfileUpdateDTO.java
Labels: :health_worker: fix, :sparkles: feat

#37 [feat] 이메일 인증 api 구현
  build.gradle
  src/main/java/trend/project/api/code/status/ErrorStatus.java
  src/main/java/trend/project/api/exception/handler/EmailCategoryHandler.java
  src/main/java/trend/project/config/SecurityConfig.java
  src/main/java/trend/project/service/MailService.java
  src/main/java/trend/project/web/controller/MailController.java
  src/main/resources/application.yml
Labels: :sparkles: feat

#38 [feat] 기획서 CRUD 관련 API 구현
  src/main/java/trend/project/converter/PlanConverter.java
  src/main/java/trend/project/domain/Location.java
  src/main/java/trend/project/domain/Plan.java
  src/main/java/trend/project/service/planService/PlanService.java
  src/main/java/trend/project/service/planService/PlanServiceImpl.java
  src/main/java/trend/project/web/controller/planController/PlanController.java
  src/main/java/trend/project/web/dto/planDTO/PlanDTO.java
Labels: :sparkles: feat

#41 [feat] setAllowedOrigins 에 도메인 추가
  src/main/java/trend/project/config/SecurityConfig.java
Labels: :health_worker: fix

#42 [feat] 메인화면 API 구현
  src/main/java/trend/project/config/SecurityConfig.java
  src/main/java/trend/project/converter/PlanMainConverter.java
  src/main/java/trend/project/domain/Member.java
  src/main/java/trend/project/domain/Plan.java
  src/main/java/trend/project/domain/PlanPosterImage.java
  src/main/java/trend/project/domain/Ranking.java
  src/main/java/trend/project/repository/MemberRepository.java
  src/main/java/trend/project/repository/RankingRepository.java
  src/main/java/trend/project/repository/planRepository/PlanRepository.java
  src/main/java/trend/project/service/RankingService.java
  src/main/java/trend/project/service/memberService/MemberServiceImpl.java
  src/main/java/trend/project/service/planService/PlanMainPageService.java
  src/main/java/trend/project/service/planService/PlanMainPageServiceImpl.java
  src/main/java/trend/project/web/controller/HealthCheckController.java
  src/main/java/trend/project/web/controller/RankingController.java
  src/main/java/trend/project/web/controller/planController/PlanMainPageController.java
  src/main/java/trend/project/web/dto/planDTO/PlanBannerDTO.java
  src/main/java/trend/project/web/dto/planDTO/PlanMainPageDTO.java
Labels: :sparkles: feat

#43 [feat] 댓글 CRUD API 구현
  src/main/java/trend/project/api/code/status/ErrorStatus.java
  src/main/java/trend/project/api/exception/handler/CommentCategoryHandler.java
  src/main/java/trend/project/converter/CommentConverter.java
  src/main/java/trend/project/domain/Comment.java
  src/main/java/trend/project/domain/enumClass/CommentType.java
  src/main/java/trend/project/repository/CommentRepository.java
  src/main/java/trend/project/service/commentService/CommentService.java
  src/main/java/trend/project/service/commentService/CommentServiceImpl.java
  src/main/java/trend/project/web/controller/commentController/CommentController.java
  src/main/java/trend/project/web/dto/commentDTO/CommentDTO.java
Labels: :sparkles: feat

#48 [fix] plan location 양방향 매핑
  src/main/java/trend/project/domain/Plan.java
  src/main/java/trend/project/service/planService/PlanServiceImpl.java
Labels: :health_worker: fix

#49 [feat] 같은 지역 다른 기획서 조회 API 구현 및 엔드포인트 수정
  src/main/java/trend/project/config/SecurityConfig.java
  src/main/java/trend/project/converter/PlanConverter.java
  src/main/java/trend/project/converter/PlanDetailConverter.java
  src/main/java/trend/project/domain/Plan.java
  src/main/java/trend/project/repository/planRepository/PlanRepository.java
  src/main/java/trend/project/service/planService/PlanDetailService.java
  src/main/java/trend/project/service/planService/PlanDetailServiceImpl.java
  src/main/java/trend/project/service/planService/PlanPosterServiceImpl.java
  src/main/java/trend/project/service/planService/PlanService.java
  src/main/java/trend/project/service/planService/PlanServiceImpl.java
  src/main/java/trend/project/web/controller/planController/PlanController.java
  src/main/java/trend/project/web/controller/planController/PlanDetailController.java
  src/main/java/trend/project/web/dto/planDTO/PlanDetailDTO.java
Labels: :sparkles: feat, :pencil2: chore

#50 [feat] 게시글 카테고리 별 조회 api 구현
  src/main/java/trend/project/config/SecurityConfig.java
  src/main/java/trend/project/domain/Ranking.java
  src/main/java/trend/project/domain/enumClass/RankingCategory.java
  src/main/java/trend/project/repository/RankingRepository.java
  src/main/java/trend/project/repository/planRepository/PlanRepository.java
  src/main/java/trend/project/service/RankingService.java
  src/main/java/trend/project/service/planService/PlanByCategoryService.java
  src/main/java/trend/project/service/planService/PlanByCategoryServiceImpl.java
  src/main/java/trend/project/service/planService/PlanMainPageServiceImpl.java
  src/main/java/trend/project/validation/annotation/CategoryNameValid.java
  src/main/java/trend/project/validation/validator/CategoryNameValidator.java
  src/main/java/trend/project/web/controller/RankingController.java
  src/main/java/trend/project/web/controller/planController/PlanByCategoryController.java
  src/main/java/trend/project/web/dto/planDTO/PlanCategoryPageDTO.java
Labels: :sparkles: feat

#52 [fix] 기획서 상세 조회 시 실제 댓글 수 미반영 오류 수정
  src/main/java/trend/project/domain/Comment.java
  src/main/java/trend/project/domain/Plan.java
  src/main/java/trend/project/service/commentService/CommentServiceImpl.java
  src/main/java/trend/project/service/planService/PlanDetailServiceImpl.java
Labels: :health_worker: fix

#54 [feat] Sentry 로그 분석기 구현
  build.gradle
  src/main/java/trend/project/ProjectApplication.java
  src/main/java/trend/project/api/code/status/ErrorStatus.java
  src/main/java/trend/project/api/exception/ExceptionAdvice.java
  src/main/java/trend/project/config/SecurityConfig.java
  src/main/java/trend/project/config/SentryConfig.java
  src/main/java/trend/project/config/SwaggerConfig.java
  src/main/java/trend/project/web/controller/HealthCheckController.java
  src/main/resources/application.yml
Labels: :sparkles: feat

#57 [fix] 회원 프로필 조회 무한 참조 오류 해결
  src/main/java/trend/project/service/memberService/MemberServiceImpl.java
  src/main/java/trend/project/web/dto/memberDTO/MemberGetProfileDTO.java
Labels: :health_worker: fix

#58 [feat] 댓글 및 기획서 좋아요 기능 구현
  src/main/java/trend/project/domain/Comment.java
  src/main/java/trend/project/domain/Plan.java
  src/main/java/trend/project/repository/commentRepository/CommentLikesRepository.java
  src/main/java/trend/project/repository/commentRepository/CommentRepository.java
  src/main/java/trend/project/repository/planRepository/PlanLikesRepository.java
  src/main/java/trend/project/service/commentService/CommentLikesService.java
  src/main/java/trend/project/service/commentService/CommentLikesServiceImpl.java
  src/main/java/trend/project/service/commentService/CommentServiceImpl.java
  src/main/java/trend/project/service/planService/PlanLikesService.java
  src/main/java/trend/project/service/planService/PlanLikesServiceImpl.java
  src/main/java/trend/project/web/controller/commentController/CommentLikesController.java
  src/main/java/trend/project/web/controller/planController/PlanLikesController.java
  src/main/java/trend/project/web/dto/commentDTO/CommentDTO.java
  src/main/java/trend/project/web/dto/planDTO/PlanDTO.java
Labels: :sparkles: feat

#60 [feat] 인증/인가 명세 수정
  src/main/java/trend/project/config/SwaggerConfig.java
  src/main/java/trend/project/web/controller/RankingController.java
  src/main/java/trend/project/web/controller/memberController/MemberController.java
  src/main/java/trend/project/web/controller/memberController/MemberImageController.java
  src/main/java/trend/project/web/controller/planController/PlanMainPageController.java
Labels: :pencil2: chore

#63 [fix] CORS 수정
  src/main/java/trend/project/config/SecurityConfig.java
  src/main/java/trend/project/web/dto/planDTO/PlanSearchDTO.java
Labels: :wrench: fix

#64 [feat] 게시글 검색 조회 API 구현
  src/main/java/trend/project/config/SecurityConfig.java
  src/main/java/trend/project/repository/planRepository/PlanRepository.java
  src/main/java/trend/project/service/planService/PlanMainPageService.java
  src/main/java/trend/project/service/planService/PlanMainPageServiceImpl.java
  src/main/java/trend/project/service/planService/PlanSearchService.java
  src/main/java/trend/project/service/planService/PlanSearchServiceImpl.java
  src/main/java/trend/project/web/controller/planController/PlanMainPageController.java
  src/main/java/trend/project/web/controller/planController/PlanSearchController.java
  src/main/java/trend/project/web/dto/planDTO/PlanSearchDTO.java
Labels: :sparkles: feat

#66 [fix] null 값 처리
  src/main/java/trend/project/service/planService/PlanByCategoryServiceImpl.java
  src/main/java/trend/project/service/planService/PlanMainPageServiceImpl.java
  src/main/java/trend/project/service/planService/PlanSearchServiceImpl.java
Labels: :wrench: fix

#68 [feat] 이미지 링크 수정
  src/main/java/trend/project/converter/PlanMainConverter.java
  src/main/java/trend/project/web/dto/planDTO/PlanMainPageDTO.java
Labels: :pencil2: chore

#70 [feat] 좋아요 상태 변수 추가
  src/main/java/trend/project/service/commentService/CommentLikesServiceImpl.java
  src/main/java/trend/project/service/planService/PlanLikesServiceImpl.java
  src/main/java/trend/project/web/dto/commentDTO/CommentDTO.java
  src/main/java/trend/project/web/dto/planDTO/PlanDTO.java
Labels: :pencil2: chore

#72 [feat] 응답객체에 PK 추가
  src/main/java/trend/project/converter/PlanMainConverter.java
  src/main/java/trend/project/service/planService/PlanMainPageServiceImpl.java
  src/main/java/trend/project/service/planService/PlanSearchServiceImpl.java
  src/main/java/trend/project/web/dto/planDTO/PlanCategoryPageDTO.java
  src/main/java/trend/project/web/dto/planDTO/PlanMainPageDTO.java
  src/main/java/trend/project/web/dto/planDTO/PlanSearchDTO.java
Labels: :pencil2: chore

#74 [feat] 기업 회원가입 로직 수정 & 비밀번호 수정 API 수정
  src/main/java/trend/project/config/SecurityConfig.java
  src/main/java/trend/project/service/companyService/CompanyServiceImpl.java
  src/main/java/trend/project/service/memberService/MemberServiceImpl.java
  src/main/java/trend/project/web/controller/HealthCheckController.java
  src/main/java/trend/project/web/dto/CompanyJoinDTO.java
  src/main/java/trend/project/web/dto/memberDTO/MemberProfileFindDTO.java
Labels: :pencil2: chore

#75 [feat] 게시글 전체 검색 API 구현
  src/main/java/trend/project/repository/planRepository/PlanRepository.java
  src/main/java/trend/project/service/planService/PlanSearchService.java
  src/main/java/trend/project/service/planService/PlanSearchServiceImpl.java
  src/main/java/trend/project/web/controller/planController/PlanSearchController.java
  src/main/java/trend/project/web/dto/planDTO/PlanMainPageDTO.java
Labels: :sparkles: feat

#77 [feat] 회원 검색 로직 구현
  src/main/java/trend/project/config/SecurityConfig.java
  src/main/java/trend/project/repository/MemberRepository.java
  src/main/java/trend/project/service/memberService/MemberService.java
  src/main/java/trend/project/service/memberService/MemberServiceImpl.java
  src/main/java/trend/project/web/controller/memberController/MemberController.java
  src/main/java/trend/project/web/dto/memberDTO/MemberSearchDTO.java
Labels: :sparkles: feat

#80 [fix] 리프레시 토큰 samestie 오류 해결
  src/main/java/trend/project/filter/LoginFilter.java
  src/main/java/trend/project/web/controller/memberController/MemberController.java
Labels: :wrench: fix

#81 [feat] 회원정보 수정 API 기능 구현
  src/main/java/trend/project/domain/Member.java
  src/main/java/trend/project/service/memberService/MemberProfileFixService.java
  src/main/java/trend/project/service/memberService/MemberProfileFixServiceImpl.java
  src/main/java/trend/project/web/controller/memberController/MemberProfileFixController.java
  src/main/java/trend/project/web/dto/memberDTO/MemberProfileFixDTO.java
Labels: :sparkles: feat

#83 [chore] 이미지 엔티티 수정 및 서비스 계층 수정
  src/main/java/trend/project/domain/CompanyProfileImage.java
  src/main/java/trend/project/domain/MemberProfileImage.java
  src/main/java/trend/project/domain/PlanBannerImage.java
  src/main/java/trend/project/domain/PlanPosterImage.java
  src/main/java/trend/project/service/companyService/CompanyProfileImageService.java
  src/main/java/trend/project/service/companyService/CompanyProfileImageServiceImpl.java
  src/main/java/trend/project/service/memberService/MemberProfileImageService.java
  src/main/java/trend/project/service/memberService/MemberProfileImageServiceImpl.java
  src/main/java/trend/project/service/planService/PlanBannerService.java
  src/main/java/trend/project/service/planService/PlanBannerServiceImpl.java
  src/main/java/trend/project/service/planService/PlanPosterService.java
  src/main/java/trend/project/service/planService/PlanPosterServiceImpl.java
Labels: :pencil2: chore

#84 [feat] 팔로우 기능 구현
  src/main/java/trend/project/domain/Member.java
  src/main/java/trend/project/domain/MemberFollow.java
  src/main/java/trend/project/domain/MemberFollower.java
  src/main/java/trend/project/repository/FollowRepository.java
  src/main/java/trend/project/repository/FollowerRepository.java
  src/main/java/trend/project/service/followService/FollowService.java
  src/main/java/trend/project/service/followService/FollowServiceImpl.java
  src/main/java/trend/project/web/controller/followController/FollowController.java
  src/main/java/trend/project/web/dto/FollowDTO.java
Labels: :sparkles: feat

#90 [feat] 회원 탈퇴 복구 API 구현
  src/main/java/trend/project/domain/Member.java
  src/main/java/trend/project/service/memberService/MemberService.java
  src/main/java/trend/project/service/memberService/MemberServiceImpl.java
  src/main/java/trend/project/web/controller/memberController/MemberController.java
Labels: :sparkles: feat

#92 [feat] 회원 검색기록 기능 구현
  src/main/java/trend/project/config/SecurityConfig.java
  src/main/java/trend/project/domain/Member.java
  src/main/java/trend/project/domain/SearchHistory.java
  src/main/java/trend/project/repository/SearchHistoryRepository.java
  src/main/java/trend/project/service/SearchHistoryService.java
  src/main/java/trend/project/service/SearchHistoryServiceImpl.java
  src/main/java/trend/project/service/planService/PlanSearchService.java
  src/main/java/trend/project/service/planService/PlanSearchServiceImpl.java
  src/main/java/trend/project/web/controller/SearchHistoryController.java
  src/main/java/trend/project/web/controller/planController/PlanSearchController.java
  src/main/java/trend/project/web/dto/HistoryDTO.java
Labels: :sparkles: feat

#95 [feat] 기업정보 관리 API 구현
  src/main/java/trend/project/domain/Company.java
  src/main/java/trend/project/domain/Member.java
  src/main/java/trend/project/service/companyService/CompanyProfileFixService.java
  src/main/java/trend/project/service/companyService/CompanyProfileFixServiceImpl.java
  src/main/java/trend/project/service/companyService/CompanyService.java
  src/main/java/trend/project/service/companyService/CompanyServiceImpl.java
  src/main/java/trend/project/web/controller/companyController/CompanyController.java
  src/main/java/trend/project/web/controller/companyController/CompanyProfileFixController.java
  src/main/java/trend/project/web/controller/followController/FollowController.java
Labels: :sparkles: feat

#97 [fix] id 리스폰스에 추가
  src/main/java/trend/project/service/planService/PlanByCategoryServiceImpl.java
Labels: :wrench: fix

#99 [chore] follow username으로 하도록 수정
  src/main/java/trend/project/service/followService/FollowService.java
  src/main/java/trend/project/service/followService/FollowServiceImpl.java
  src/main/java/trend/project/web/controller/followController/FollowController.java
Labels: :pencil2: chore

#100 [doc] 리드미 작성
  README.md
Labels: :page_facing_up: doc

#103 [chore] 리프레시토큰 수정
  src/main/java/trend/project/filter/LoginFilter.java
Labels: :pencil2: chore

#104 [fix] 지역 수정
  src/main/java/trend/project/repository/planRepository/PlanRepository.java
  src/main/java/trend/project/service/planService/PlanByCategoryServiceImpl.java
Labels: :wrench: fix

#105 [fix] ranking Id 수정
  src/main/java/trend/project/service/planService/PlanMainPageServiceImpl.java
Labels: :wrench: fix
